team_id: "Unique Team ID"
managed_services:
  cosmosdb_sql:
    name: "NameoftheCosmosDB-Account"
    other_properties: "Other properties"
    databases:
      - db_name: "Database1"
        containers:
          - container_name: "Container1"
            partition_key: "/partition_key"
            other_properties: "Other properties"
          - container_name: "Container2"
            partition_key: "/partition_key"
            other_properties: "Other properties"
      - db_name: "Database2"
        containers:
          - container_name: "Container3"
            partition_key: "/partition_key"
            other_properties: "Other properties"
          - container_name: "Container4"
            partition_key: "/partition_key"
            other_properties: "Other properties"
