name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      port_payload:
        description: 'Main Port Payload'
        required: true
        type: string

jobs:
  process-json:
    runs-on: ubuntu-latest

    steps:
      - name: Parse and process port payload
        run: |
          echo "Parsing JSON input..."
          # Access the input variable
          JSON_STRING='${{ github.event.inputs.port_payload }}'
          
          echo "Input JSON String: $JSON_STRING"

          # Process the JSON string
          #echo "$JSON_STRING" | jq -r '.payload.properties.pull_request | "Object: \n\(. | to_entries | .[] | "  \(.key): \(.value)")"'
      # Step 3: Simulate some action (e.g., build, test, etc.)
      - name: Simulate action (e.g., build, test, etc.)
        run: |
          echo "Running some custom actions..."
          sleep 3  # simulate some processing time
          echo "Action completed successfully!"
      # Step 7: Optionally: Final status update
      - name: Final Status Update in Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io    # Port API Key (Set in GitHub Secrets)
          runId: ${{  fromJson(inputs.port_payload).context.runId }}
          logMessage: Pull request created successfully for  https://www.google.com "${{ inputs.name }}" 
          status: "SUCCESS"                         # Final status
          summary: "This workflow was triggered and completed successfully https://www.google.com."
          link: "https://google.com,https://bing.com"            # Link to be included
          operation: PATCH_RUN
