name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      port_payload:
        description: 'Main Port Payload'
        required: true
        type: string

jobs:
  process-json:
    runs-on: ubuntu-latest

    steps:
      - name: Parse and process port payload
        run: |
          echo "Parsing JSON input..."
          # Access the input variable
          JSON_STRING='${{ github.event.inputs.port_payload }}'
          
          echo "Input JSON String: $JSON_STRING"

          # Process the JSON string
          echo "$JSON_STRING" | jq -r '.payload.properties.pull_request | "Object: \n\(. | to_entries | .[] | "  \(.key): \(.value)")"'
